"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Names referenced by autogenerated column definitions: the PostgreSQL JSONB
# variant and Text (used inside JSONB's astext_type). Custom TypeDecorators are
# rendered as plain sa.* types by render_item in env.py, so no app imports here.
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
