"""initial schema

Revision ID: 6c21c7a69c6f
Revises:
Create Date: 2026-08-17 21:21:54.865047
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Names referenced by autogenerated column definitions: our custom types, the
# PostgreSQL JSONB variant, and Text (used inside JSONB's astext_type).
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "6c21c7a69c6f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("application_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifacts_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_artifacts_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_type"), ["type"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_actor"), ["actor"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "preferences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("source_job_id", sa.String(length=200), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("remote", sa.String(length=20), nullable=False),
        sa.Column("employment_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "requirements_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "salary_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedupe_group", sa.String(length=64), nullable=True),
        sa.Column(
            "raw_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_job_id", name="uq_job_source_identity"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_company"), ["company"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_dedupe_group"), ["dedupe_group"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_title"), ["title"], unique=False)

    op.create_table(
        "candidate_facts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("provenance", sa.String(length=20), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_fact_confidence_range"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_facts_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_candidate_facts_category"), ["category"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.String(length=200), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_evidence_source_id"), ["source_id"], unique=False)

    op.create_table(
        "job_matches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("eligibility", sa.String(length=20), nullable=False),
        sa.Column(
            "hard_constraints_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "components_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "strengths_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "gaps_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "weights_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_match_score_range"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "job_id", name="uq_match_candidate_job"),
    )
    with op.batch_alter_table("job_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_matches_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_matches_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_matches_score"), ["score"], unique=False)

    op.create_table(
        "resumes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_path", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("derived_from_id", sa.String(length=64), nullable=True),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("is_original", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["derived_from_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "version", name="uq_resume_candidate_version"),
    )
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resumes_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_resumes_sha256"), ["sha256"], unique=False)
        batch_op.create_index(
            "uq_resume_single_original",
            ["candidate_id"],
            unique=True,
            sqlite_where=sa.text("is_original IS 1"),
            postgresql_where=sa.text("is_original IS 1"),
        )

    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("approved_resume_id", sa.String(length=64), nullable=True),
        sa.Column("cover_letter_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmation_ref", sa.String(length=300), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("stop_reason", sa.String(length=40), nullable=True),
        sa.Column("stop_detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["approved_resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["cover_letter_artifact_id"], ["artifacts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "job_id", name="uq_application_candidate_job"),
        sa.UniqueConstraint("idempotency_key", name="uq_application_idempotency"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_applications_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_applications_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_status"), ["status"], unique=False)

    op.create_table(
        "fact_evidence",
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fact_id"], ["candidate_facts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fact_id", "evidence_id"),
    )
    op.create_table(
        "resume_edits",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("resume_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("operation", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.String(length=200), nullable=False),
        sa.Column("old_text", sa.Text(), nullable=False),
        sa.Column("new_text", sa.Text(), nullable=False),
        sa.Column(
            "evidence_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resume_edits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resume_edits_resume_id"), ["resume_id"], unique=False)

    op.create_table(
        "application_answers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("application_id", sa.String(length=64), nullable=False),
        sa.Column("field", sa.String(length=300), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("user_verified", sa.Boolean(), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "field", name="uq_answer_application_field"),
    )
    with op.batch_alter_table("application_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_answers_application_id"), ["application_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_answers_application_id"))

    op.drop_table("application_answers")
    with op.batch_alter_table("resume_edits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resume_edits_resume_id"))

    op.drop_table("resume_edits")
    op.drop_table("fact_evidence")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_status"))
        batch_op.drop_index(batch_op.f("ix_applications_job_id"))
        batch_op.drop_index(batch_op.f("ix_applications_candidate_id"))

    op.drop_table("applications")
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_resume_single_original",
            sqlite_where=sa.text("is_original IS 1"),
            postgresql_where=sa.text("is_original IS 1"),
        )
        batch_op.drop_index(batch_op.f("ix_resumes_sha256"))
        batch_op.drop_index(batch_op.f("ix_resumes_candidate_id"))

    op.drop_table("resumes")
    with op.batch_alter_table("job_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_matches_score"))
        batch_op.drop_index(batch_op.f("ix_job_matches_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_matches_candidate_id"))

    op.drop_table("job_matches")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_source_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_candidate_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("candidate_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_facts_category"))
        batch_op.drop_index(batch_op.f("ix_candidate_facts_candidate_id"))

    op.drop_table("candidate_facts")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_title"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index(batch_op.f("ix_jobs_dedupe_group"))
        batch_op.drop_index(batch_op.f("ix_jobs_company"))

    op.drop_table("jobs")
    op.drop_table("candidates")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_type"))
        batch_op.drop_index(batch_op.f("ix_artifacts_sha256"))
        batch_op.drop_index(batch_op.f("ix_artifacts_application_id"))

    op.drop_table("artifacts")
    # ### end Alembic commands ###
